version: '3.9'

services:
    jenkins:
        build:
            context: ./jenkins
            args:
                JENKINS_PORT: 4242
        network_mode: host
        env_file:
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        secrets:
            - nm_eip_front_ssh
            - nm_eip_back_ssh

    registry:
        image: registry:2
        container_name: eip-deploy_registry
        ports:
            - "5000:5000"
        volumes:
            - registry:/var/lib/registry
        restart: always

volumes:
    registry: null

secrets:
    nm_eip_front_ssh:
        file: ./secrets/nm_eip_front_ssh
    nm_eip_back_ssh:
        file: ./secrets/nm_eip_back_ssh
