version: '3.9'

services:
    jenkins:
        build:
            context: ./jenkins
            args:
                JENKINS_PORT: 4242
        ports:
            - "4242:4242"
        env_file:
            - .env
        networks:
            - kubernetes
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        secrets:
            - nm_eip_front_ssh
            - nm_eip_back_ssh

    registry:
        image: registry:2
        container_name: eip-deploy_registry
        ports:
            - "127.0.0.1:5000:5000"
        networks:
            - registry
        volumes:
            - registry:/var/lib/registry
        restart: always

networks:
    kubernetes: null
    registry: null

volumes:
    registry: null

secrets:
    nm_eip_front_ssh:
        file: ./secrets/nm_eip_front_ssh
    nm_eip_back_ssh:
        file: ./secrets/nm_eip_back_ssh
