version: '3.9'

services:
    jenkins-controller:
        build:
            context: ./jenkins
            args:
                JENKINS_PORT: 4242
        container_name: eip-deploy-jenkins-controller
        env_file:
            - .env
        ports:
            - "4242:4242"
        networks:
            - jenkins
        secrets:
            - nm_eip_front_ssh
            - nm_users_back_ssh
            - nm_maestro_ssh
            - nm_chouf_ssh
        restart: always

    jenkins-agent:
        build:
            context: ./jenkins/agent
            args:
                JENKINS_PORT: 4242
        networks:
            - jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins-controller
        restart: always

networks:
    jenkins: null

secrets:
    nm_eip_front_ssh:
        file: ./secrets/nm_eip_front_ssh
    nm_users_back_ssh:
        file: ./secrets/nm_users_back_ssh
    nm_maestro_ssh:
        file: ./secrets/nm_maestro_ssh
    nm_chouf_ssh:
        file: ./secrets/nm_chouf_ssh
