version: '3.9'

services:
    jenkins-controller:
        build:
            context: ./jenkins
            args:
                JENKINS_PORT: 4242
        container_name: eip-deploy-jenkins-controller
        ports:
            - "4242:4242"
        env_file:
            - .env
        networks:
            - jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - kubernetes-config:/root/.kube
        secrets:
            - nm_eip_front_ssh
            - nm_users_back_ssh
            - nm_maestro_ssh

    jenkins-agent:
        build:
            context: ./jenkins/agent
            args:
                JENKINS_PORT: 4242
        depends_on:
            - jenkins-controller
        networks:
            - jenkins
            - kubernetes
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - kubernetes-config:/root/.kube:ro
        restart: always

    registry:
        image: registry:2
        container_name: eip-deploy-registry
        ports:
            - "127.0.0.1:5000:5000"
        networks:
            - registry
        volumes:
            - registry:/var/lib/registry
        restart: always

networks:
    jenkins: null
    kubernetes: null
    registry: null

volumes:
    kubernetes-config: null
    registry: null

secrets:
    nm_eip_front_ssh:
        file: ./secrets/nm_eip_front_ssh
    nm_users_back_ssh:
        file: ./secrets/nm_users_back_ssh
    nm_maestro_ssh:
        file: ./secrets/nm_maestro_ssh
