version: '3'

services:
    jenkins:
        build:
            context: ./jenkins
            args:
                JENKINS_PORT: 4242
        ports:
            - "4242:4242"
        env_file:
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins:/var/jenkins_home
        secrets:
            - nm_eip_front_ssh
            - nm_eip_back_ssh
        restart: always

    registry:
        image: registry:2
        ports:
            - "127.0.0.1:5001:5000"
        volumes:
            - registry:/var/lib/registry
        restart: always

volumes:
    jenkins: null
    registry: null

secrets:
    nm_eip_front_ssh:
        file: ./secrets/nm_eip_front_ssh
    nm_eip_back_ssh:
        file: ./secrets/nm_eip_back_ssh
