apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-back-development

spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-back
      runEnv: development
  template:
    metadata:
      labels:
        app: users-back
        runEnv: development
    spec:
      nodeSelector:
        runEnv: development
      restartPolicy: Always
      containers:
        - name: users-back-development
          image: localhost:5000/users-back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: THIS_STRING_IS_REPLACED_DURING_BUILD
            - name: PORT
              value: "8080"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
