apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-back-production

spec:
  replicas: 3
  selector:
    matchLabels:
      app: users-back
      runEnv: production
  template:
    metadata:
      labels:
        app: users-back
        runEnv: production
    spec:
      nodeSelector:
        runEnv: production
      restartPolicy: Always
      containers:
        - name: users-back-production
          image: localhost:5000/users-back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: THIS_STRING_IS_REPLACED_DURING_BUILD
            - name: MONGODB_URI
              value: mongodb://root:mongo_root_password_1234@eipdb:27017
            - name: PORT
              value: "8080"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 4
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 1
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 15
          #   successThreshold: 1
          #   failureThreshold: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
