apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-db-development

spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
      runEnv: development
  template:
    metadata:
      labels:
        app: users-db
        runEnv: development
    spec:
      nodeSelector:
        runEnv: development
      restartPolicy: Always
      containers:
        - name: users-db-development
          image: mongo:6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongo_root_password_1234
            - name: MONGO_INITDB_DATABASE
              value: eipdb
          startupProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
