kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://eip-deploy-registry:5000"]

nodes:
  - role: control-plane

  - role: worker
    labels:
      runEnv: production
    extraPortMappings:
      # CLIENT
      - containerPort: 30008
        hostPort: 80
      # SERVER
      - containerPort: 30808
        hostPort: 8080

  - role: worker
    labels:
      runEnv: development
    extraPortMappings:
      # CLIENT
      - containerPort: 30008
        hostPort: 81
      # SERVER
      - containerPort: 30808
        hostPort: 8081
