kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://eip-deploy_registry:5000"]

nodes:
  - role: control-plane
    extraPortMappings:
      # CLIENT
      - containerPort: 30008
        hostPort: 80
      # SERVER
      # - containerPort: 30808
      #   hostPort: 8080
