kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  apiServerPort: 6445

nodes:
  - role: control-plane
    extraPortMappings:
      # CLIENT
      - containerPort: 30008
        hostPort: 80
      # SERVER
      - containerPort: 30808
        hostPort: 8080
