apiVersion: apps/v1
kind: Deployment

metadata:
  name: cached-db-production

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cached-db
      runEnv: production
  template:
    metadata:
      labels:
        app: cached-db
        runEnv: production
    spec:
      nodeSelector:
        runEnv: production
      restartPolicy: Always
      containers:
        - name: cached-db-production
          image: mongo:6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: nuage_malin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongo_nuage_malin_RuDaVErate
            - name: MONGO_INITDB_DATABASE
              value: maestro
          startupProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
