jenkins:
  systemMessage: Nuage Malin

  securityRealm:
    local:
      allowsSignup: false

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: Admin
            permissions:
              - Overall/Administer
          - name: Manager
            description: Can read, build and cancel jobs
            permissions:
              - Overall/Read
              - Job/Read
              - Job/Build
              - Job/Cancel
          - name: Developer
            description: Can read and cancel jobs
            permissions:
              - Overall/Read
              - Job/Read
              - Job/Cancel
          - name: Visitor
            description: Read-only on jobs
            permissions:
              - Overall/Read
              - Job/Read

jobs:
  - file: ${JENKINS_HOME}/job_dsl/jenkins.groovy

security:
  GlobalJobDslSecurityConfiguration:
    useScriptSecurity: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: eip_front_production
              passphrase:
              description: SSH deploy key to clone front repository
              privateKeySource:
                directEntry:
                  privateKey: ${readFile:/run/secrets/nm_eip_front_ssh_key}
