jenkins:
  systemMessage: Nuage Malin

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: Jenkins Agent
          password: cc9c494ca8afcc43a0db7e8aa65662f6

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: Agent
            description: Only destinated to Jenkins Agents
            permissions:
              - Overall/Read
              - Agent/Connect
            assignments:
              - Jenkins Agent
          - name: Admin
            permissions:
              - Overall/Administer
          - name: Manager
            description: Can read, build and cancel jobs
            permissions:
              - Overall/Read
              - Job/Read
              - Job/Build
              - Job/Cancel
          - name: Developer
            description: Can read and cancel jobs
            permissions:
              - Overall/Read
              - Job/Read
              - Job/Cancel
          - name: Visitor
            description: Read-only on jobs
            permissions:
              - Overall/Read
              - Job/Read

  labelString: "master"
  mode: EXCLUSIVE
  numExecutors: 0
  nodes:
    - permanent:
        name: "Nuage Malin Agent"
        labelString: nuage-malin
        nodeDescription: Agent to run Nuage Malin jobs
        remoteFS: /home/nuage_malin
        retentionStrategy: always
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: remoting

jobs:
  - file: ${JENKINS_HOME}/job_dsl/jenkins.groovy

security:
  GlobalJobDslSecurityConfiguration:
    useScriptSecurity: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: eip_front
              passphrase: nm_eip_front_ssh
              description: SSH deploy key to clone front repository
              privateKeySource:
                directEntry:
                  privateKey: ${readFile:/run/secrets/nm_eip_front_ssh}
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: users_back
              passphrase: nm_users_back_ssh
              description: SSH deploy key to clone users-back repository
              privateKeySource:
                directEntry:
                  privateKey: ${readFile:/run/secrets/nm_users_back_ssh}
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: maestro
              passphrase: nm_maestro_ssh
              description: SSH deploy key to clone maestro repository
              privateKeySource:
                directEntry:
                  privateKey: ${readFile:/run/secrets/nm_maestro_ssh}
