name: Protect branches

on:
  push:
    branches:
      - sprint-2/protect-branches

jobs:
  protect:
    runs-on: ubuntu-22.04
    if: ${{ github.event.head_commit.name != 'GitHub' && github.event.head_commit.email != 'noreply@github.com' }}
    steps:
      # Setup
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: DEBUG
        run: echo "${{ toJson(github.event) }}"

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run
      - name: Reset commits
        run: git reset --hard ${{ github.event.before }}

      - name: Force update HEAD
        run: git push --force
